server:
  port: 8082
  # 从反向代理读取相关的HTTP Header:
  forward-headers-strategy: native
spring:
  datasource:
    url: jdbc:mysql://localhost/grammar
    username: db_chris
    password: ABCaiChen

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:./resources/

swagger2:
  host: 47.101.160.248:82