server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/grammar
    username: root
    password: aa19881203
  
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:../resources/




